# Generated by Django 5.0.6 on 2024-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='letter',
            field=models.CharField(max_length=12),
        ),
    ]
