# Generated by Django 5.0.6 on 2024-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_number_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='Imagen_pokemon',
            field=models.ImageField(blank=True, max_length=1, null=True, upload_to='pokemon_images/'),
        ),
    ]
