# Generated by Django 5.0.6 on 2024-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_pokemon_imagen_pokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='Imagen_pokemon',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images/'),
        ),
    ]
